baseURL = "https://ranashekhar192.github.io/New_mtm6407-static-site-ranashekhar192/"
languageCode = "en-us"
title = "Shekhar Rana's Personal Site"
theme = "ananke"
paginate = 10
relativeURLs = true
canonifyURLs = true

[params]
  customCSS = ["css/styles.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
